# =============================================
# 1. ESTRUCTURA DE TABLAS (Firebase Data Connect)
# =============================================

# 1.1 Tabla MAQUINAS
type Maquinas @table(name: "MAQUINAS") {
  id: Int!
  nombre: String! @col(dataType: "varchar(100)")
  tipo: String @col(dataType: "varchar(50)")
  estado: Int! @default(value: 0)
  descripcion: String @col(dataType: "text")
  operativa: Int! @default(value: 1)
}

# 1.2 Tabla USUARIO
type Usuario @table(name: "USUARIO") {
  id: Int!
  nombre: String! @col(dataType: "varchar(100)")
  dni: String @unique @col(dataType: "varchar(20)")
  email: String @unique @col(dataType: "varchar(100)")
  contraseniaHash: String @col(name: "CONTRASEÑA_HASH", dataType: "varchar(255)")
  telefono: String @col(dataType: "varchar(20)")
  premium: Boolean @default(value: false)
  fechaIniPrem: Date @col(name: "FECHA_INI_PREM")
  fechaFinPrem: Date @col(name: "FECHA_FIN_PREM")
  fechaReg: Date! @col(name: "FECHA_REG") @default(expr: "request.time")
  admin: Int! @default(value: 0)
}

# 1.3 Tabla PLATOS
type Platos @table(name: "PLATOS") {
  id: Int!
  idUsuario: Usuario
  nombre: String! @col(dataType: "varchar(100)")
  descripcion: String @col(dataType: "text")
  calorias: Float @col(name: "CALORIAS")
  imagenUrl: String @col(name: "IMAGEN_URL", dataType: "varchar(255)")
  fechaSubida: Date! @col(name: "FECHA_SUBIDA") @default(expr: "request.time")
  visibilidad: Boolean @default(value: true)
}

# 1.4 Tabla RESERVAS
type Reservas @table(name: "RESERVAS") {
  id: Int!
  idUsuario: Usuario!
  idMaquina: Maquinas!
  fecha: Date
  horaInicio: String @col(name: "HORA_INICIO", dataType: "time")
  horaFin: String @col(name: "HORA_FIN", dataType: "time")
  estado: Boolean @default(value: true)
}

# 1.5 Tabla PESO_USUARIO
type PesoUsuario @table(name: "PESO_USUARIO") {
  id: Int!
  idUsuario: Usuario!
  peso: Float! @col(name: "PESO")
  fecha: Date
}

# 1.6 Tabla PAGOS
type Pagos @table(name: "PAGOS") {
  id: Int!
  idUsuario: Usuario!
  monto: Int! @col(name: "monto", dataType: "bigint")
  fechaPago: Date @col(name: "fecha_pago")
  tipo: String @col(name: "tipo", dataType: "varchar(50)")
  metodoPago: String @col(name: "metodo_pago", dataType: "varchar(25)")
}

# 1.7 Tabla RECOMENDACIÓN_DIARIA
type RecomendacionDiaria @table(name: "RECOMENDACION_DIARIA") {
  id: Int!
  idPlatoFk: Platos!
  fecha: Date
}