package com.example.trainium

object DbTables {
    const val USUARIOS = "usuarios"
    const val MAQUINAS = "maquinas"
    const val PLATOS = "platos"
    const val PAGOS = "pagos"
    const val RESERVAS = "reservas"
    const val PESO_USUARIO = "peso_usuario"
    const val FOTO = "foto"
}

object DbColumns {
    const val ID = "id"
    const val ID_USUARIO = "id_usuario"
    const val ID_MAQUINA = "id_maquina"
    const val NOMBRE = "nombre"
    const val EMAIL = "email"
    const val DNI = "dni"
    const val TELEFONO = "telefono"
    const val CONTRASENIA_HASH = "contraseniaHash"
    const val ADMIN = "admin"
    const val PREMIUM = "premium"
    const val FECHA_INI_PREM = "fecha_ini_prem"
    const val FECHA_FIN_PREM = "fecha_fin_prem"
    const val FOTO = "foto"
    const val TIPO = "tipo"
    const val ESTADO = "estado"
    const val DESCRIPCION = "descripcion"
    const val OPERATIVA = "operativa"
    const val MANTENIMIENTO_DESDE = "mantenimiento_desde"
    const val MANTENIMIENTO_HASTA = "mantenimiento_hasta"
    const val IMAGEN_URL = "imagen_url"
    const val VISIBILIDAD = "visibilidad"
    const val ACEPTADO = "aceptado"
    const val FECHA_SUBIDA = "fecha_subida"
    const val HORA_INICIO = "hora_inicio"
    const val HORA_FIN = "hora_fin"
    const val FECHA = "fecha"
    const val MONTO = "monto"
    const val FECHA_PAGO = "fecha_pago"
    const val METODO_PAGO = "metodo_pago"
    const val PESO = "peso"
}
